### ISSUE TITLE
Dark text on Firefox

### ISSUE THREAD

**Issue by fabricyo** [johnendz/Firefox-Extension-Telegram-Dark#1]
Hi, I loved this plugin, is quite helpful as I have astigmatism. But I just have one issue:
- On the message box, where I write the message, the text is in black. So is hard to see what I'm writing... Anyway, I know that's just a line in style.css.

Anyway, cheers.
![image](https://user-images.githubusercontent.com/21691524/81621101-f1089a00-93c3-11ea-9ee9-0a9d93f24884.png)

**Comment by johnendz** [comment]
Ok, I will investigate

**Comment by johnendz** [comment]
Version 2.1 is now available for download.

**Comment by fabricyo** [comment]
Oh thank you very much my dear sir.
